stages:
  - build
  - test
  - verify

binary:
  stage: build
  image: golang:1.18-buster
  script: go build

lint:
  stage: test
  image: golangci/golangci-lint:v1.37
  script:
    - golangci-lint run -v -E golint -E gofmt -E goconst -E interfacer -E gocritic -E gocognit -E gocyclo

end-to-end:
  stage: verify
  image: golang:1.18-buster
  script:
    - go test main*.go

benchmark:
  stage: verify
  image: golang:1.18-buster
  script:
    - go test ./... -run=Bench -bench=. -benchtime=10x -timeout 0
  when: manual
