stages:
  - test
  - benchmark

lint:
  stage: test
  image: golangci/golangci-lint:v1.25.0
  script:
    - golangci-lint run -v -E golint -E gofmt -E goconst -E interfacer -E gocritic -E gocognit -E gocyclo

end-to-end:
  stage: test
  image: golang:1.14-buster
  script:
    - go test main*.go

benchmark:
  stage: benchmark
  image: golang:1.14-buster
  script:
    - go test ./... -run=Bench -bench=. -benchtime=10x -timeout 0
  when: manual
